[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
frankcoin = "FJu4SvyPdLYtCmRSgjZi3ShJvoyEPvjdC1MPhz44ngdF"

[programs.devnet]
frankcoin = "FJu4SvyPdLYtCmRSgjZi3ShJvoyEPvjdC1MPhz44ngdF"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
