[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
frankcoin = "61yBp4FQSXq6qxS1Scny8LRBNDLDoNQBKupofVSyyHL8"

[programs.devnet]
frankcoin = "61yBp4FQSXq6qxS1Scny8LRBNDLDoNQBKupofVSyyHL8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
